'use strict';

/**
 * @ngdoc function
 * @name biprojectDevelopmentApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the biprojectDevelopmentApp
 */
angular.module('biprojectDevelopmentApp')
.factory('testFactory', function(){
  return {
    test: function(){
      return [
      {"$id":"1",
      "InputTypeId":"121",
      "InputType":"TextBox",
      "Access":"YES",
      "Status": "In Progress",
      "Answer":"",
      "OptionList":"",
      "OptionListOrientation":"",
      "ToolTip":"",
      "ToolTipPlacement":"",
      "ToolTipTrigger": "",
      "PlaceHolder":"",
      "Label":"General Information",
      "TemplateName":"RX",
      "GridConfig":"",
      "GridValue": ""},

      {"$id":"2",
      "InputTypeId":"122",
      "InputType":"TextArea",
      "Access":"YES",
      "Status": "Done",
      "Answer":"Hello World!",
      "OptionList":"",
      "OptionListOrientation":"",
      "ToolTip":"",
      "ToolTipPlacement":"",
      "ToolTipTrigger": "",
      "PlaceHolder":"",
      "Label":"Gretting",
      "TemplateName":"RX",
      "GridConfig":"",
      "GridValue": ""},

      {"$id":"3",
      "InputTypeId":"123",
      "InputType":"CheckList",
      "Access":"No",
      "Status": "Done",
      "Answer":"1",
      "OptionList":"1,2,3,4",
      "OptionListOrientation":"inline",
      "ToolTip":"",
      "ToolTipPlacement":"",
      "ToolTipTrigger": "",
      "PlaceHolder":"",
      "Label":"General List",
      "TemplateName":"RX",
      "GridConfig":"",
      "GridValue": ""},

      {"$id":"4",
      "InputTypeId":"124",
      "InputType":"RadioList",
      "Access":"YES",
      "Status": "Not Started",
      "Answer":"",
      "OptionList":"1,2,3,4",
      "OptionListOrientation":"inline",
      "ToolTip":"",
      "ToolTipPlacement":"",
      "ToolTipTrigger": "",
      "PlaceHolder":"",
      "Label":"General Radio List",
      "TemplateName":"RX",
      "GridConfig":"",
      "GridValue": ""},

      {"$id":"5",
      "InputTypeId":"125",
      "InputType":"Grid",
      "Access":"YES",
      "Status": "",
      "Answer":"",
      "OptionList":"",
      "OptionListOrientation":"",
      "ToolTip":"",
      "ToolTipPlacement":"",
      "ToolTipTrigger": "",
      "PlaceHolder":"",
      "Label":"General Grid",
      "TemplateName":"RX",
      "GridConfig":"Configuration1, Configuration 2, Configuration3",
      "GridValue": "1"},

      {"$id":"6",
      "InputTypeId":"126",
      "InputType":"DropDown",
      "Access":"No",
      "Status": "In Progress",
      "Answer":"",
      "OptionList":"Start, Complete",
      "OptionListOrientation":"",
      "ToolTip":"",
      "ToolTipPlacement":"",
      "ToolTipTrigger": "",
      "PlaceHolder":"",
      "Label":"General DropDown",
      "TemplateName":"RX",
      "GridConfig":"",
      "GridValue": ""},

      {"$id":"7",
      "InputTypeId":"127",
      "InputType":"Title",
      "Access":"Yes",
      "Status": "",
      "Answer":"",
      "OptionList":"",
      "OptionListOrientation":"",
      "ToolTip":"",
      "ToolTipPlacement":"",
      "ToolTipTrigger": "",
      "PlaceHolder":"",
      "Label":"Title of Project",
      "TemplateName":"RX",
      "GridConfig":"",
      "GridValue": ""},

      {"$id":"8",
      "InputTypeId":"128",
      "InputType":"Subtitle",
      "Access":"YES",
      "Status": "",
      "Answer":"",
      "OptionList":"",
      "OptionListOrientation":"",
      "ToolTip":"",
      "ToolTipPlacement":"",
      "ToolTipTrigger": "",
      "PlaceHolder":"",
      "Label":"Subtitle of Project",
      "TemplateName":"RX",
      "GridConfig":"",
      "GridValue": ""},

      {"$id":"9",
      "InputTypeId":"129",
      "InputType":"Picture",
      "Access":"YES",
      "Status": "",
      "Answer":"",
      "OptionList":"",
      "OptionListOrientation":"",
      "ToolTip":"Logo of the Company",
      "ToolTipPlacement":"Right",
      "ToolTipTrigger": "Hover",
      "PlaceHolder":"",
      "Label":"Picture/ Logo of Company",
      "TemplateName":"RX",
      "GridConfig":"",
      "GridValue": ""}
    ];
    }
  };
});
